### Notify
POST http://localhost:7438/notify
###
GET http://localhost:7438/notify

### Updated
POST http://localhost:7438/updated

### PHP Notify
POST http://localhost/themekitHotReload/notify
###
GET http://localhost/themekitHotReload/notify

### PHP Updated
POST http://localhost/themekitHotReload/updated
